[demo_snow_cim_change_incidents]
search = sourcetype=demo:snow:incident cim_data_model=Change cim_dataset=All_Changes

[demo_snow_cim_change_requests]
search = sourcetype=demo:snow:change cim_data_model=Change cim_dataset=All_Changes

[demo_snow_cim_task_ci_relationships]
search = sourcetype=demo:snow:task_ci cim_data_model=Change cim_dataset=All_Changes

[demo_snow_cim_inventory]
search = sourcetype=demo:snow:cmdb_ci cim_data_model=Inventory cim_dataset=All_Inventory

[demo_snow_es_identity]
search = sourcetype=demo:snow:user cim_data_model=Identity

[demo_es_mission_control_source]
search = sourcetype=demo:es:incident
