[eventtype=demo_snow_cim_change_incidents]
change = enabled
ticket = enabled
incident = enabled

[eventtype=demo_snow_cim_change_requests]
change = enabled
ticket = enabled

[eventtype=demo_snow_cim_task_ci_relationships]
change = enabled
ticket = enabled

[eventtype=demo_snow_cim_inventory]
inventory = enabled

[eventtype=demo_snow_es_identity]
identity = enabled

[eventtype=demo_es_mission_control_source]
incident = enabled
