[servicenow_incidents_demo]
filename = servicenow_incidents.csv
case_sensitive_match = false

[servicenow_changes_demo]
filename = servicenow_changes.csv
case_sensitive_match = false

[servicenow_cmdb_demo]
filename = servicenow_cmdb.csv
case_sensitive_match = false

[servicenow_users_demo]
filename = servicenow_users.csv
case_sensitive_match = false

[servicenow_task_ci_demo]
filename = servicenow_task_ci.csv
case_sensitive_match = false

[es_incidents_demo]
filename = es_incidents.csv
case_sensitive_match = false
