[snow_cim_change_incidents]
search = sourcetype=snow:incident cim_data_model=Change cim_dataset=All_Changes

[snow_cim_change_requests]
search = sourcetype=snow:change_request cim_data_model=Change cim_dataset=All_Changes

[snow_cim_task_ci_relationships]
search = sourcetype=snow:task_ci cim_data_model=Change cim_dataset=All_Changes

[snow_cim_inventory]
search = sourcetype=snow:cmdb_ci cim_data_model=Inventory cim_dataset=All_Inventory

[snow_es_identity]
search = sourcetype=snow:sys_user cim_data_model=Identity
