[eventtype=snow_cim_change_incidents]
change = enabled
ticket = enabled
incident = enabled

[eventtype=snow_cim_change_requests]
change = enabled
ticket = enabled

[eventtype=snow_cim_task_ci_relationships]
change = enabled
ticket = enabled

[eventtype=snow_cim_inventory]
inventory = enabled

[eventtype=snow_es_identity]
identity = enabled
